import { useState } from "react";
import { Check, Clock3, Heart, Leaf, MessageCircle, MapPin, Menu, Phone, ShieldCheck, X, Facebook, Instagram, Linkedin, Plane, Megaphone, Activity } from "lucide-react";

const WHATSAPP = "244943984724";
const phoneLink = "tel:+244943984724";


function scrollToId(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); }

const serviceDetails = {
  janotour: { label: "JANOTOUR LDA", title: "Turismo e Viagem", intro: "Planeamos viagens com acompanhamento próximo, desde a escolha do destino até ao regresso.", items: ["Roteiros personalizados em Angola e no exterior", "Reservas, transfers e apoio ao viajante", "Experiências culturais, lazer e turismo de grupo"], proof: "Exemplos de soluções: escapadinhas, viagens de negócios, excursões e experiências à medida." },
  visivel: { label: "VISÍVEL - Marketing e Publicidade Lda.", title: "Marketing e Publicidade", intro: "Damos forma, clareza e presença às marcas que querem ser reconhecidas.", items: ["Identidade visual, logótipos e materiais de marca", "Conteúdo para redes sociais, campanhas e anúncios", "Fotografia, vídeo, comunicação e materiais promocionais"], proof: "Entregáveis: planos de comunicação, campanhas, peças digitais, impressos e conteúdos para lançamento." },
  saude: { label: "MELHORE A SUA SAÚDE", title: "Nutracêuticos e Bem-estar", intro: "Soluções e produtos para apoiar rotinas de cuidado, nutrição e bem-estar.", items: ["Aloe vera, suplementos e produtos de nutrição", "Cuidados pessoais e higiene diária", "Orientação para escolher produtos adequados à sua rotina"], proof: "Produtos em destaque: Forever Aloe Vera Gel, Forever Bright Toothgel, Aloe Bits N’ Peaches e Fields of Greens." },
  feel: { label: "FEEL EMOTION", title: "Eventos e Experiências", intro: "Criamos momentos com conceito, produção e atenção a cada detalhe.", items: ["Planeamento e produção de eventos corporativos", "Decoração, ambientação e coordenação no local", "Lançamentos, celebrações e experiências de marca"], proof: "Soluções: conceito criativo, fornecedores, cronograma, produção e acompanhamento do evento." }
};

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [selectedService, setSelectedService] = useState<keyof typeof serviceDetails | null>(null);
  const whatsapp = (message: string) => window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(message)}`, "_blank");

  return <div className="min-h-screen bg-[#f8f7f1] text-[#183b2b] selection:bg-[#c9e6b7]">
    <div className="topline"><div className="container flex items-center justify-between gap-4 text-[11px] uppercase tracking-[0.18em]"><span>Luanda · Angola</span><span className="hidden sm:inline">Atendimento: segunda a sábado · 09h às 15h</span><a href={phoneLink} className="font-semibold">+244 943 984 724</a></div></div>
    <header className="sticky top-0 z-30 border-b border-[#dce7d8]/80 bg-[#f8f7f1]/90 backdrop-blur-xl"><div className="container flex h-[76px] items-center justify-between">
      <a href="#inicio" className="flex items-center gap-3"><img className="brand-logo-final" src={`${import.meta.env.BASE_URL}janota-teias-assets/janota-original-clean.webp`} alt="JANOTA TEIAS — Comércio e Serviços"/></a>
      <nav className="site-nav hidden items-center gap-8 text-sm font-medium md:flex"><button onClick={() => scrollToId("servicos")}>Serviços</button><button onClick={() => scrollToId("sobre")}>A nossa essência</button><button onClick={() => scrollToId("contacto")}>Contacto</button></nav>
      <button className="hidden rounded-full bg-[#194b34] px-5 py-3 text-xs font-bold uppercase tracking-[0.15em] text-white transition hover:-translate-y-0.5 hover:bg-[#245d40] sm:block" onClick={() => whatsapp("Olá, gostaria de saber mais sobre os produtos da JANOTA TEIAS.")}>Falar connosco </button>
      <button className="md:hidden" aria-expanded={menuOpen} aria-label={menuOpen ? "Fechar menu" : "Abrir menu"} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</button>
    </div>{menuOpen && <div className="mobile-menu container border-t border-[#dce7d8] py-4 md:hidden"><div className="flex flex-col gap-4 text-sm"><button className="text-left" onClick={() => {scrollToId("servicos"); setMenuOpen(false)}}>Serviços</button><button className="text-left" onClick={() => {scrollToId("sobre"); setMenuOpen(false)}}>A nossa essência</button><button className="text-left" onClick={() => {scrollToId("contacto"); setMenuOpen(false)}}>Contacto</button></div></div>}</header>

    <main id="inicio">
      <section className="hero-shell hero-background" style={{ backgroundImage: `linear-gradient(90deg,rgba(243,247,251,.98) 0%,rgba(243,247,251,.92) 36%,rgba(243,247,251,.50) 68%,rgba(243,247,251,.16) 100%), url(${import.meta.env.BASE_URL}janota-teias-assets/grupo-hero.webp)` }}><div className="container relative z-10 flex min-h-[650px] items-center py-16 lg:py-20"><div className="relative z-10 max-w-xl"><div className="eyebrow">Um grupo angolano com visão</div><h1 className="mt-6 font-display text-[clamp(3.2rem,7vw,6.8rem)] font-medium leading-[0.88] tracking-[-0.065em]">Pessoas, marcas e experiências <em className="text-[#d97838]">em movimento.</em></h1><p className="mt-7 max-w-md text-[17px] leading-8 text-[#587064]">Um grupo angolano com soluções para viajar melhor, comunicar com impacto e viver com mais saúde.</p><p className="service-subtitle mt-4 max-w-lg text-xs font-bold uppercase tracking-[0.14em] text-[#24543c]">Turismo e viagens · Marketing e publicidade · Nutracêuticos · Eventos em Luanda</p><div className="mt-9 flex flex-wrap gap-3"><button className="rounded-full bg-[#d97838] px-6 py-4 text-sm font-bold text-white shadow-[0_12px_30px_-14px_#b45620] transition hover:-translate-y-1 hover:bg-[#c9692c]" onClick={() => scrollToId("servicos")}>Conhecer os serviços </button><button className="rounded-full border border-[#aac3ae] bg-white/40 px-6 py-4 text-sm font-bold text-[#24543c] transition hover:bg-white" onClick={() => whatsapp("Olá! Gostaria de receber aconselhamento sobre o produto ideal para mim.")}>Aconselhamento gratuito</button></div><div className="mt-12 flex items-center gap-6 border-t border-[#cfddd0] pt-5 text-xs text-[#65786c]"><span className="flex items-center gap-2"><ShieldCheck size={16} className="text-[#5c9c60]"/> Seleção de confiança</span><span className="flex items-center gap-2"><MapPin size={16} className="text-[#5c9c60]"/> Entrega em Luanda</span></div></div></div></section>

      <section className="border-y border-[#dce7d8] bg-[#edf4e9] py-5"><div className="container grid gap-4 sm:grid-cols-3"><div className="flex items-center gap-3"><Leaf size={20} className="text-[#5d9c5f]"/><span><strong className="block text-sm">Soluções integradas</strong><small className="text-[#6c7e70]">Experiência em várias áreas</small></span></div><div className="flex items-center gap-3"><Heart size={20} className="text-[#d97838]"/><span><strong className="block text-sm">Relações que perduram</strong><small className="text-[#6c7e70]">Atendimento próximo e humano</small></span></div><div className="flex items-center gap-3"><MessageCircle size={20} className="text-[#5d9c5f]"/><span><strong className="block text-sm">Presença em Luanda</strong><small className="text-[#6c7e70]">Fale diretamente com a nossa equipa</small></span></div></div></section>

      <section id="servicos" className="services-section"><div className="container py-24"><div className="max-w-2xl"><div className="eyebrow">Um grupo. Várias possibilidades.</div><h2 className="mt-4 font-display text-5xl leading-[.95] tracking-[-.055em] md:text-6xl">Soluções que <em className="text-[#d97838]">movem</em> pessoas e negócios.</h2><p className="mt-6 max-w-xl text-[17px] leading-8 text-[#63766a]">Conheça as nossas áreas de atuação, pensadas para acompanhar diferentes momentos da sua vida e do crescimento da sua marca.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3"><article className="service-card"><img src={`${import.meta.env.BASE_URL}janota-teias-assets/janotour.webp`} loading="lazy" decoding="async" alt="Turismo e viagem em Angola"/><div className="service-overlay"><span className="service-icon"><Plane size={22}/></span><small>JANOTOUR LDA</small><h3>Turismo e<br/>Viagem</h3><p>Descubra novos destinos com experiências feitas à sua medida.</p><button onClick={() => setSelectedService("janotour")}>Saber mais</button></div></article><article className="service-card"><img src={`${import.meta.env.BASE_URL}janota-teias-assets/visivel-sem-pessoa.webp`} loading="lazy" decoding="async" alt="Marketing e publicidade Visível"/><div className="service-overlay"><span className="service-icon"><Megaphone size={22}/></span><small>VISÍVEL - Marketing e Publicidade Lda.</small><h3>Marcas que<br/>ficam visíveis.</h3><p>Estratégia, criatividade e comunicação para dar força à sua marca.</p><button onClick={() => setSelectedService("visivel")}>Saber mais</button></div></article><article className="service-card"><img src={`${import.meta.env.BASE_URL}janota-teias-assets/saude.webp`} loading="lazy" decoding="async" alt="Nutracêuticos e bem-estar"/><div className="service-overlay"><span className="service-icon"><Activity size={22}/></span><small>MELHORE A SUA SAÚDE</small><h3>Bem-estar<br/>com propósito.</h3><p>Nutracêuticos e escolhas conscientes para uma rotina mais equilibrada.</p><button onClick={() => setSelectedService("saude")}>Saber mais</button></div></article><article className="service-card"><img src={`${import.meta.env.BASE_URL}janota-teias-assets/feelemotion.webp`} loading="lazy" decoding="async" alt="Feel Emotion - organização e produção de eventos"/><div className="service-overlay"><span className="service-icon"><Heart size={22}/></span><small>FEEL EMOTION</small><h3>Momentos que<br/>ficam para sempre.</h3><p>Conceção e produção de eventos com emoção, detalhe e identidade.</p><button onClick={() => setSelectedService("feel")}>Saber mais</button></div></article></div></div></section>

      <section id="sobre" className="nature-section"><div className="container grid items-center gap-14 py-24 lg:grid-cols-[1fr_0.9fr]"><div className="relative order-2 lg:order-1"><img src={`${import.meta.env.BASE_URL}janota-teias-assets/visivel-sem-pessoa.webp`} alt="Equipa criativa num estúdio de marketing em Luanda" loading="lazy" decoding="async" className="rounded-[28px] shadow-[0_28px_70px_-35px_#153c28]"/><div className="stat-card"><strong>360°</strong><span>visão<br/>integrada</span></div></div><div className="order-1 lg:order-2"><div className="eyebrow light">A nossa essência</div><h2 className="mt-5 font-display text-5xl leading-[0.95] tracking-[-0.055em] text-white md:text-6xl">Um grupo com <em className="text-[#e9ae78]">propósito.</em></h2><p className="mt-7 text-[17px] leading-8 text-[#c5d8c8]">A JANOTA TEIAS - COMÉRCIO E SERVIÇOS (SU), LDA reúne projetos que criam valor em diferentes áreas: turismo, comunicação, eventos e saúde. Trabalhamos com proximidade, criatividade e compromisso para transformar boas ideias em experiências memoráveis.</p><ul className="mt-8 space-y-4 text-sm text-[#e0eee1]">{["Atendimento humano e personalizado", "Soluções para pessoas, marcas e experiências", "Presença local em Luanda, Angola"].map(item => <li key={item} className="flex items-center gap-3"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#7db47b] text-[#173b29]"><Check size={14}/></span>{item}</li>)}</ul><button className="mt-9 rounded-full border border-[#7eae83] px-6 py-3 text-sm font-bold text-white transition hover:bg-white hover:text-[#183b2b]" onClick={() => whatsapp("Olá! Gostaria de conhecer melhor a JANOTA TEIAS.")}>Conheça a JANOTA TEIAS </button></div></div></section>

      <section id="contacto" className="container py-24"><div className="contact-card"><div><div className="eyebrow">Estamos por perto</div><h2 className="mt-4 max-w-xl font-display text-5xl leading-[0.95] tracking-[-0.055em] md:text-6xl">Comece hoje a cuidar melhor de si.</h2><p className="mt-5 max-w-md leading-7 text-[#63766a]">Fale connosco para conhecer os produtos, esclarecer dúvidas ou receber uma recomendação personalizada.</p></div><div className="contact-details"><a href={phoneLink} className="contact-line"><Phone size={20}/><span><small>Telefone</small><strong>+244 943 984 724 · +244 953 322 103</strong></span></a><div className="contact-line"><Clock3 size={20}/><span><small>Horário de atendimento</small><strong>09h00 — 15h00</strong></span></div><div className="contact-line"><MapPin size={20}/><span><small>Localização</small><strong>Luanda, Angola</strong></span></div></div></div></section>
    </main>
      {selectedService && <div className="service-modal-backdrop" role="presentation" onClick={() => setSelectedService(null)}><div className="service-modal" role="dialog" aria-modal="true" aria-labelledby="service-modal-title" onClick={(event) => event.stopPropagation()}><button className="service-modal-close" aria-label="Fechar detalhes" onClick={() => setSelectedService(null)}><X size={20}/></button><div className="eyebrow">{serviceDetails[selectedService].label}</div><h2 id="service-modal-title" className="mt-3 font-display text-4xl leading-tight text-[#17314b]">{serviceDetails[selectedService].title}</h2><p className="mt-4 text-base leading-7 text-[#61778b]">{serviceDetails[selectedService].intro}</p><div className="mt-6 grid gap-3">{serviceDetails[selectedService].items.map((item) => <div key={item} className="service-detail-item"><Check size={16}/><span>{item}</span></div>)}</div><div className="service-proof mt-6"><strong>O que podemos apresentar</strong><p>{serviceDetails[selectedService].proof}</p></div><button className="mt-7 rounded-full bg-[#2177c7] px-6 py-3 text-sm font-bold text-white transition hover:bg-[#185f9f]" onClick={() => whatsapp(`Olá! Gostaria de receber mais detalhes sobre ${serviceDetails[selectedService].title}.`)}>Pedir informações no WhatsApp</button></div></div>}
    <footer className="border-t border-[#dce7d8] bg-[#edf4e9] py-8"><div className="container flex flex-col justify-between gap-5 text-xs text-[#708276] sm:flex-row sm:items-center"><span>© {new Date().getFullYear()} JANOTA TEIAS - COMÉRCIO E SERVIÇOS (SU), LDA</span><div className="flex items-center gap-3"><span className="mr-1">Siga-nos</span><a className="social-icon" href="https://www.facebook.com/" target="_blank" rel="noreferrer" aria-label="Facebook"><Facebook size={16}/></a><a className="social-icon" href="https://www.instagram.com/" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={16}/></a><a className="social-icon" href="https://www.linkedin.com/" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={16}/></a></div><span>Soluções que conectam, qualidade que protege.</span><span className="footer-nif">NIF: 5002143704</span></div></footer>
    <button className="whatsapp-float" aria-label="Falar no WhatsApp" onClick={() => whatsapp("Olá, JANOTA TEIAS! Gostaria de saber mais sobre os produtos.")}><img className="whatsapp-logo-float" src="https://cdn.simpleicons.org/whatsapp/FFFFFF" alt="WhatsApp"/></button>
  </div>;
}
